### PR TITLE
Typescript definitions

### PR DESCRIPTION
**Pull request by fstojanac**
Added Typescript definitions to keep editor and test happy

### CODE REVIEW

**Comment by fstojanac** [comment]
Thanks!

Can you please bump the version and publish it to the npm? :) Sorry, I had forgotten do to that change earlier.

**Comment by azizhk** [comment]
Hi @Liroo please publish new release. :sweat_smile:

**Comment by Liroo** [comment]
I'm not really maintaining this repository but I will be glad to make admin someone here.

Anyway I published a new release :)

**Comment by wong2** [comment]
But the types are not exported?

**Pull request merged**
