### PR TITLE
Update package.json ot include types

### PR DESCRIPTION
**Pull request by Sharcoux**
It's good to have a typing file, it's better to share it with the rest of the world ;)

### CODE REVIEW

**Comment by div-dog** [comment]
Would love to see this merged!

**Comment by mrAnomalyy** [comment]
Awaiting this to be merged! Please!

**Comment by SimonIT** [comment]
@Liroo it would be great if you could merge this PR :)

**Comment by aprilmintacpineda** [comment]
Please do

**Comment by tonhao-dev** [comment]
Up vote

**Comment by asurare** [comment]
@Liroo Is there smth blocking the merge of this PR ?

**Comment by Sharcoux** [comment]
The project is probably just abandoned.

**Comment by camcelroy** [comment]
@Liroo please

**Comment by Sharcoux** [comment]
I noticed some performance concerns with this implementation anyway. You might as well use another lib. What do you plan to use this for?

**Pull request merged**
